### ISSUE TITLE
test run error

### ISSUE THREAD

**Issue by yueduz** [kitmi/koa-webpack-dev#4]
> koa-webpack-dev@1.0.2 test /home/lei/Downloads/koa-webpack-dev-master
> mocha --harmony -R spec -t 5000 test/*.js

  koa-middleware-webpack
    bvt
info: Compiling assets...
info: Compiling assets...
info: Rebuild completed.
      1) should rebuild and serve index.html
info: Compiling assets...
info: Compiling assets...
info: Rebuild completed.
      2) should work when using external config file
info: Compiling assets...
info: Compiling assets...
info: Rebuild completed.
      ✓ should rebuild and serve bundle.js (1337ms)
info: Compiling assets...
info: Compiling assets...
info: Rebuild completed.
      ✓ should return 404 while requesting non-exist file (1301ms)

  2 passing (7s)
  2 failing

  1) koa-middleware-webpack bvt should rebuild and serve index.html:
     Error: expected body 'TypeError: Path must be a string. Received undefined' to match /<title>My app<\/title>/
      at error (node_modules/supertest/lib/test.js:265:13)
      at Test._assertBody (node_modules/supertest/lib/test.js:188:18)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:691:12)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) koa-middleware-webpack bvt should work when using external config file:
     Error: expected body 'TypeError: Path must be a string. Received undefined' to match /<title>My app<\/title>/
      at error (node_modules/supertest/lib/test.js:265:13)
      at Test._assertBody (node_modules/supertest/lib/test.js:188:18)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:691:12)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Test failed.  See above for more details.

**Comment by rockie** [comment]
please down grade node to v5. its a issue of webpack.
refer to: https://github.com/webpack/webpack/issues/2463
